export const AuthMock = {
    User: {
        RoleID: 0,
        MemberOf: null,
        Selected: false,
        PasswordInput: null,
        ReNewPassword: null,
        NewPassword: null,
        Order: 0,
        Disabled: false,
        RoleLetters: null,
        ID: 1,
        UserName: "admin",
        FullName: "Admin System",
        Password: "F168A5253E9CB803E6B5010912CE3C7F0A58DD38",
        Email: "lengoc@ezs.vn",
        Address: "6/72 Khuong Trung, Dong da, Ha noi",
        Phone: "0915161518",
        CreateDate: "2021-12-17T09:56:17.797",
        Avatar: "",
        Birthday: "2021-12-17T09:56:17.797",
        YahooID: "",
        Gender: 0,
        Status: 0,
        GroupUser: null,
        IsBuiltin: 1,
        Level: "",
        Auth2TokenIds: "",
    },
    Stocks: [{
            LinkToMe: "/quan-ly-co-so-778.aspx",
            LinkTagPToMe: "/tag/quan-ly-co-so-778.aspx",
            PrNameFr: null,
            ToMe: "/kho.aspx",
            ToMeID: "/kho-778.aspx",
            Thumbnail_web: "/Upload/image/null.gif",
            Prex: null,
            Gender: null,
            RawThumb: "https://cser.vn/Upload/image/null.gif",
            ID: 778,
            ApplicationKey: "kho",
            ParentID: 0,
            Title: "Quản lý cơ sở",
            Desc: "Quản lý cơ sở",
            Order: 0,
            CreateDate: "2017-07-10T09:37:00.81",
            Type: 0,
            LanguageID: 0,
            Status: 1,
            Thumbnail: "null.gif",
            Thumbnail2: "null.gif",
            TitleSEO: null,
            DescSEO: null,
            KeySEO: null,
            LinkSEO: null,
            IsBuiltIn: 1,
            NameFr: "kho",
            IsPublic: 1,
            Value: null,
            IsRight: 1,
            Rel: null,
            Count: 0,
            BrandName: "",
            Map: "",
        },
        {
            LinkToMe: "/0981883338-8975.aspx",
            LinkTagPToMe: "/tag/0981883338-8975.aspx",
            PrNameFr: "kho",
            ToMe: "/.aspx",
            ToMeID: "/-8975.aspx",
            Thumbnail_web: "/Upload/image/2021/02/05/0_image_210205-102157ZCy.png",
            Prex: null,
            Gender: null,
            RawThumb: "https://cser.vn/Upload/image/2021/02/05/0_image_210205-102157ZCy.png",
            ID: 8975,
            ApplicationKey: "kho",
            ParentID: 778,
            Title: "Cser Hà Nội",
            Desc: "22/42 Vũ Ngọc Phan, Đống Đa, HN",
            Order: 0,
            CreateDate: "2021-02-05T10:21:57.277",
            Type: 0,
            LanguageID: 0,
            Status: 0,
            Thumbnail: "2021/02/05/0_image_210205-102157ZCy.png",
            Thumbnail2: "2021/02/05/0_image_210205-102157zT2.png",
            TitleSEO: "",
            DescSEO: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.456787991938!2d105.80825751541903!3d21.01440119364303!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab6176bd4321%3A0x5db62fa79dcf1cd5!2zMjIsIDQyIFbFqSBOZ-G7jWMgUGhhbiwgS2h1IHThuq1wIHRo4buDIE5hbSBUaMOgbmggQ8O0bmcsIEzDoW5nIEjhuqEsIMSQ4buRbmcgxJBhLCBIw6AgTuG7mWksIFZp4buHdCBOYW0!5e0!3m2!1svi!2s!4v1617693355188!5m2!1svi!2s",
            KeySEO: "",
            LinkSEO: "0981883338",
            IsBuiltIn: 0,
            NameFr: "",
            IsPublic: 1,
            Value: "1234",
            IsRight: 0,
            Rel: "",
            Count: 0,
            BrandName: "",
            Map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.4567155746972!2d105.808251715332!3d21.014404093643275!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab6176bd4321%3A0x5db62fa79dcf1cd5!2zMjIsIDQyIFbFqSBOZ-G7jWMgUGhhbiwgTMOhbmcgSOG6oSwgxJDhu5FuZyDEkGEsIEjDoCBO4buZaSwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2s!4v1638761362506!5m2!1svi!2s",
        },
        {
            LinkToMe: "/0977629595-10053.aspx",
            LinkTagPToMe: "/tag/0977629595-10053.aspx",
            PrNameFr: "kho",
            ToMe: "/.aspx",
            ToMeID: "/-10053.aspx",
            Thumbnail_web: "/Upload/image/2021/12/18/0_image_211218-055835du5.png",
            Prex: null,
            Gender: null,
            RawThumb: "https://cser.vn/Upload/image/2021/12/18/0_image_211218-055835du5.png",
            ID: 10053,
            ApplicationKey: "kho",
            ParentID: 778,
            Title: "Cser Hồ Chí Minh",
            Desc: "12 Võ Thị Sáu, Quận 1, Thành phố Hồ Chí Minh",
            Order: 0,
            CreateDate: "2021-12-18T05:58:35.35",
            Type: 0,
            LanguageID: 0,
            Status: 0,
            Thumbnail: "2021/12/18/0_image_211218-055835du5.png",
            Thumbnail2: "2021/12/18/0_image_211218-055835oYx.png",
            TitleSEO: "",
            DescSEO: "",
            KeySEO: "",
            LinkSEO: "0977629595",
            IsBuiltIn: 0,
            NameFr: "",
            IsPublic: 1,
            Value: "1234",
            IsRight: 0,
            Rel: "",
            Count: 0,
            BrandName: "",
            Map: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.2593418973574!2d106.69310431526033!3d10.791438261866167!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x317528cb6d795ffd%3A0xfa0e9cca4a1738e4!2zMTIgVsO1IFRo4buLIFPDoXUsIFTDom4gxJDhu4tuaCwgUXXhuq1uIDEsIFRow6BuaCBwaOG7kSBI4buTIENow60gTWluaCwgVmnhu4d0IE5hbQ!5e0!3m2!1svi!2s!4v1639803870329!5m2!1svi!2s",
        },
    ],
    Online: null,
    AllGroups: [{
            IsCurrent: false,
            StockID: 8975,
            Name: "Cser Hà Nội",
            Users: [{
                    RoleID: 0,
                    MemberOf: null,
                    Selected: false,
                    PasswordInput: null,
                    ReNewPassword: null,
                    NewPassword: null,
                    Order: 0,
                    Disabled: false,
                    RoleLetters: ["LT", "KHO", "KT"],
                    ID: 4725,
                    UserName: "ngoclb",
                    FullName: "Lê Bảo Ngọc",
                    Password: "65B7E7489D8546D3E36C16F25FA40A1E00C6EFD6",
                    Email: "",
                    Address: "",
                    Phone: "",
                    CreateDate: "2021-12-18T06:01:42.777",
                    Avatar: "",
                    Birthday: "2021-12-18T06:01:42.777",
                    YahooID: "",
                    Gender: 0,
                    Status: 0,
                    GroupUser: "",
                    IsBuiltin: 0,
                    Level: "Thử việc",
                    Auth2TokenIds: "",
                },
                {
                    RoleID: 0,
                    MemberOf: null,
                    Selected: false,
                    PasswordInput: null,
                    ReNewPassword: null,
                    NewPassword: null,
                    Order: 0,
                    Disabled: false,
                    RoleLetters: ["KHO"],
                    ID: 4731,
                    UserName: "anhnx",
                    FullName: "nguyeen xuan anh",
                    Password: "DE930E76A79AFC6D25140C81EB411C6EB079901A",
                    Email: "",
                    Address: "",
                    Phone: "",
                    CreateDate: "2022-01-07T21:29:40.453",
                    Avatar: "",
                    Birthday: "2022-01-07T21:29:40.453",
                    YahooID: "",
                    Gender: 0,
                    Status: 0,
                    GroupUser: "",
                    IsBuiltin: 0,
                    Level: "",
                    Auth2TokenIds: "",
                },
                {
                    RoleID: 0,
                    MemberOf: null,
                    Selected: false,
                    PasswordInput: null,
                    ReNewPassword: null,
                    NewPassword: null,
                    Order: 0,
                    Disabled: false,
                    RoleLetters: ["GD"],
                    ID: 4730,
                    UserName: "nguyenhang",
                    FullName: "nguyen hang",
                    Password: "6F7057739E8A31CBF6585BB72102181FAFD84564",
                    Email: "",
                    Address: "",
                    Phone: "",
                    CreateDate: "2021-12-28T17:23:45.283",
                    Avatar: "",
                    Birthday: "2021-12-28T17:23:45.283",
                    YahooID: "",
                    Gender: 0,
                    Status: 0,
                    GroupUser: "",
                    IsBuiltin: 0,
                    Level: "Thử việc",
                    Auth2TokenIds: "",
                },
                {
                    RoleID: 0,
                    MemberOf: null,
                    Selected: false,
                    PasswordInput: null,
                    ReNewPassword: null,
                    NewPassword: null,
                    Order: 0,
                    Disabled: false,
                    RoleLetters: ["DV"],
                    ID: 4726,
                    UserName: "hangnp",
                    FullName: "Nguyễn Phương Hằng",
                    Password: "930559731A9605E4907E2D494C67FC5FDF1077EB",
                    Email: "",
                    Address: "",
                    Phone: "",
                    CreateDate: "2021-12-18T06:01:53.843",
                    Avatar: "",
                    Birthday: "2021-12-18T06:01:53.843",
                    YahooID: "",
                    Gender: 0,
                    Status: 0,
                    GroupUser: "",
                    IsBuiltin: 0,
                    Level: "Nhân viên chính thức",
                    Auth2TokenIds: "",
                },
                {
                    RoleID: 0,
                    MemberOf: null,
                    Selected: false,
                    PasswordInput: null,
                    ReNewPassword: null,
                    NewPassword: null,
                    Order: 0,
                    Disabled: false,
                    RoleLetters: ["DV"],
                    ID: 4727,
                    UserName: "thuta",
                    FullName: "Trần anh Thư",
                    Password: "B57039FFBA67A26F0EB9ECA726031EFE95DFA555",
                    Email: "",
                    Address: "",
                    Phone: "",
                    CreateDate: "2021-12-18T06:02:00.457",
                    Avatar: "",
                    Birthday: "2021-12-18T06:02:00.457",
                    YahooID: "",
                    Gender: 0,
                    Status: 0,
                    GroupUser: "",
                    IsBuiltin: 0,
                    Level: "Thử việc",
                    Auth2TokenIds: "",
                },
            ],
        },
        {
            IsCurrent: false,
            StockID: 10053,
            Name: "Cser Hồ Chí Minh",
            Users: [{
                    RoleID: 0,
                    MemberOf: null,
                    Selected: false,
                    PasswordInput: null,
                    ReNewPassword: null,
                    NewPassword: null,
                    Order: 0,
                    Disabled: false,
                    RoleLetters: ["GD"],
                    ID: 4730,
                    UserName: "nguyenhang",
                    FullName: "nguyen hang",
                    Password: "6F7057739E8A31CBF6585BB72102181FAFD84564",
                    Email: "",
                    Address: "",
                    Phone: "",
                    CreateDate: "2021-12-28T17:23:45.283",
                    Avatar: "",
                    Birthday: "2021-12-28T17:23:45.283",
                    YahooID: "",
                    Gender: 0,
                    Status: 0,
                    GroupUser: "",
                    IsBuiltin: 0,
                    Level: "Thử việc",
                    Auth2TokenIds: "",
                },
                {
                    RoleID: 0,
                    MemberOf: null,
                    Selected: false,
                    PasswordInput: null,
                    ReNewPassword: null,
                    NewPassword: null,
                    Order: 0,
                    Disabled: false,
                    RoleLetters: ["DV"],
                    ID: 4728,
                    UserName: "anhnp",
                    FullName: "Nguyễn Phương Anh",
                    Password: "EE1F289F1C44D6054C2EF61F2AC7351F1BC480C0",
                    Email: "",
                    Address: "",
                    Phone: "",
                    CreateDate: "2021-12-18T06:02:07.957",
                    Avatar: "",
                    Birthday: "2021-12-18T06:02:07.957",
                    YahooID: "",
                    Gender: 0,
                    Status: 0,
                    GroupUser: "",
                    IsBuiltin: 0,
                    Level: "Thử việc",
                    Auth2TokenIds: "",
                },
                {
                    RoleID: 0,
                    MemberOf: null,
                    Selected: false,
                    PasswordInput: null,
                    ReNewPassword: null,
                    NewPassword: null,
                    Order: 0,
                    Disabled: false,
                    RoleLetters: ["DV"],
                    ID: 4729,
                    UserName: "hoant",
                    FullName: "Nguyễn Thị Hoa",
                    Password: "08376913F237398023B222C882A3E801BF51BE00",
                    Email: "",
                    Address: "",
                    Phone: "",
                    CreateDate: "2021-12-18T06:02:22.27",
                    Avatar: "",
                    Birthday: "2021-12-18T06:02:22.27",
                    YahooID: "",
                    Gender: 0,
                    Status: 0,
                    GroupUser: "",
                    IsBuiltin: 0,
                    Level: "",
                    Auth2TokenIds: "",
                },
                {
                    RoleID: 0,
                    MemberOf: null,
                    Selected: false,
                    PasswordInput: null,
                    ReNewPassword: null,
                    NewPassword: null,
                    Order: 0,
                    Disabled: false,
                    RoleLetters: ["GD"],
                    ID: 4732,
                    UserName: "phuonganh",
                    FullName: "Phuong anh",
                    Password: "5E0C875C7DC7521FCA972C80121C4E4A1670B46A",
                    Email: "",
                    Address: "",
                    Phone: "",
                    CreateDate: "2022-01-08T07:07:36.563",
                    Avatar: "",
                    Birthday: "2022-01-08T07:07:36.563",
                    YahooID: "",
                    Gender: 0,
                    Status: 0,
                    GroupUser: "",
                    IsBuiltin: 0,
                    Level: "",
                    Auth2TokenIds: "",
                },
            ],
        },
    ],
    Groups: [{
        ID: 1,
        Title: "Administrator",
        Desc: "Quản trị hệ thống",
        CreateDate: "2014-07-10T00:00:00",
        IsBuiltIn: 1,
        Order: 0,
        LUONG: 0,
        PHU_CAP: 0,
        NGAY_CONG: 0,
    }, ],
    GroupsNoMode: [{
        ID: 1,
        Title: "Administrator",
        Desc: "Quản trị hệ thống",
        CreateDate: "2014-07-10T00:00:00",
        IsBuiltIn: 1,
        Order: 0,
        LUONG: 0,
        PHU_CAP: 0,
        NGAY_CONG: 0,
    }, ],
    CrStockID: 8975,
    Mode: null,
    CashNoPending: "1",
    _AllGroup: ["order", "service", "director", "store", "accountant"],
    CHAM_CONG_TINH_LUONG: false,
    Present: {
        CAN_XU_LY: {
            "0": 3,
            "8975": 12,
        },
        DAT_LICH: {
            "8975": 0,
        },
    },
};